from pathlib import Path
from datetime import datetime

from agents.maintenance_agent import build_maintenance_report


GENERATED_REPORTS_DIR = Path("reports/generated_reports")
DEFAULT_SCENARIO = "safety_critical"


def build_markdown_report(report: dict) -> str:
    """
    Convert a maintenance agent report dictionary into Markdown text.
    """
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    markdown = f"""# Maintenance Agent Report

## Report Metadata

| Field | Value |
|---|---|
| Generated at | {generated_at} |
| Vehicle ID | {report["vehicle_id"]} |
| Scenario | {report["scenario"]} |

---

## Maintenance Recommendation

| Field | Value |
|---|---|
| Failure probability | {report["failure_probability"]} |
| Cost-sensitive threshold | {report["cost_sensitive_threshold"]} |
| Recommended action | {report["recommended_action"]} |
| Severity | {report["severity"]} |
| True label binary | {report["true_label_binary"]} |

---

## Agent Reasoning

{report["agent_reasoning"]}

---

## Technical Explanation

{report["technical_explanation"]}

---

## Interpretation

The maintenance recommendation is generated by combining:

1. The predicted failure probability from the trained LightGBM baseline model.
2. The cost-sensitive threshold selected under the `{report["scenario"]}` scenario.
3. A rule-based maintenance action layer that maps risk levels to operational actions.

This report is intended as a decision-support output, not as an automatic replacement for human maintenance judgment.

---

## Next Development Steps

Future versions of this report should include:

- vehicle time-series trend charts
- comparison against fleet-level baseline behavior
- comparison against similar vehicles
- SHAP-based risk factor explanation
- cost comparison between action alternatives
- documentation-aware RAG explanation
"""
    return markdown


def save_markdown_report(
    vehicle_id: int,
    scenario_name: str = DEFAULT_SCENARIO,
    output_dir: Path = GENERATED_REPORTS_DIR,
) -> Path:
    """
    Generate and save a Markdown maintenance report for one vehicle.
    """
    report = build_maintenance_report(
        vehicle_id=vehicle_id,
        scenario_name=scenario_name,
    )

    markdown_report = build_markdown_report(report)

    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"vehicle_{vehicle_id}_report.md"

    output_path.write_text(markdown_report, encoding="utf-8")

    return output_path


def main() -> None:
    """
    Generate example reports for selected validation vehicles.
    """
    example_vehicle_ids = [10, 16, 18, 23, 45]

    for vehicle_id in example_vehicle_ids:
        output_path = save_markdown_report(
            vehicle_id=vehicle_id,
            scenario_name=DEFAULT_SCENARIO,
        )

        print(f"Saved report: {output_path}")


if __name__ == "__main__":
    main()